config/routes.rb
Myapp::Application.routes.draw do

  resources :marcas
  
  resources :modelos
  post 'modelos/get_modelos', to: 'modelos#get_modelos'
  
  resources :clientes 
  get '/search_cliente', to: "clientes#search"
  post 'clientes/verificar', to: "clientes#verificar"
  
  resources :assinaturas
  get 'assinaturas/index/:cliente_id', to: 'assinaturas#index', as: :cliente_assinaturas
 
  root to: 'static#index'
  
end

app/models/cliente.rb
class Cliente < ActiveResource::Base  
  
  self.site = "https://assinatura-api.herokuapp.com/api/v1/" 
  
  #self.site = "tcp://localhost:3001/api/v1/" 

  self.element_name = "cliente"

  has_many :assinaturas

  schema = { 'nome' => :string, 'cpf' => :string, 'email' => :string }

  self.include_format_in_path = false



end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new(nome:nil, cpf: nil, email: nil)
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    if @cliente.save
      redirect_to clientes_url, notice: I18n.t(:notice_cliente_create)
    else
      render :new 
    end

  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    if @cliente.update_attributes(cliente_params)
      redirect_to clientes_url, notice: I18n.t(:notice_cliente_update)
    else
      render :edit 
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    if @cliente.destroy
      redirect_to clientes_url, notice: I18n.t(:notice_cliente_destroy)
    else
      redirect_to clientes_url, notice: I18n.t(:notice_cliente_not_destroy)
    end
  end

  # GET /search_cliente
  def search_cliente
  end

  # POST /clientes
  def verificar
    @cliente = Cliente.find(params[:cpf_cliente]) rescue nil
    if @cliente.nil?
      @cpf_cliente = params[:cpf_cliente]
      redirect_to  new_assinatura_path, notice: "CPF do cliente nao existe, deve cadastrar-lho"
    else
      @assinaturas = Assinatura.todas
      #redirect_to cliente_assinatura_path, notice: "O cliente já existe"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id]) rescue nil
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nome, :cpf, :email)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.haml
= form_for @cliente, html: { class: "form-horizontal", role: "form", id: 'form-cliente' } do |f|
  -if @cliente.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@cliente.errors.count, "error")} prohibited this cliente from being saved:"

      %ul
        - @cliente.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label I18n.t(:cpf), class: 'col-sm-2 control-label'
    .col-sm-4
      = f.number_field :cpf, class: 'form-control'
  .form-group
    = f.label I18n.t(:nome_cliente), class: 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :nome, class: 'form-control'
  .form-group
    = f.label I18n.t(:email), class: 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :email, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-4
      = f.submit class: 'btn btn-primary'

app/views/clientes/edit.html.haml
.page-header
  = link_to clientes_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    =I18n.t(:back)

  %h1
    =I18n.t(:editing_cliente)

= render 'form'

app/views/clientes/index.html.haml
.page-header
  = link_to new_cliente_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    =I18n.t(:new_cliente)
  %h1
    =I18n.t(:listing_clientes)
.table-responsive
  %table.table.table-striped.table-bordered.table-hover#dttb
    %thead
      %tr
        %th
          =I18n.t(:nome_cliente)
        %th
          =I18n.t(:cpf)
        %th
          =I18n.t(:email)
        %th

    %tbody
      - @clientes.each do |cliente|
        %tr
          %td= cliente.nome
          %td= cliente.cpf
          %td= cliente.email
          %td
            = link_to edit_cliente_path(cliente) do
              %i.fa.fa-pencil
              &nbsp;
            = link_to cliente, data: { confirm: I18n.t(:are_you_sure_destroy_cliente) }, method: :delete do
              %i.fa.fa-trash
              &nbsp;
              &nbsp;
            - if cliente.assinaturas.any?  
              = link_to cliente_assinaturas_path(cliente.id) do
                %i.fa.fa-map-marker
                =I18n.t(:assinaturas)
 

app/views/clientes/new.html.haml
.page-header
  = link_to clientes_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    =I18n.t(:back)
  %h1
    =I18n.t(:new_cliente)

= render 'form'

app/views/clientes/search.html.haml
.page-header
  = link_to clientes_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    =I18n.t(:back)
  %h1 Verificando o CPF do Cliente
= form_tag '/clientes/verificar', method: :post, html: { class: "form-horizontal", role: "form", id: 'form-search' } do 
  .form-group
    = label_tag :cpf_cliente, I18n.t(:cpf_cliente), class: 'col-sm-2 control-label'
    .col-sm-2
      = number_field_tag :cpf_cliente, "", class: 'form-control'
    .col-sm-2
      = submit_tag I18n.t(:verificar), class: 'btn btn-primary' 

app/views/clientes/verificar.html.haml
.page-header
  = link_to new_assinatura_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    =I18n.t(:new_assinatura)
  / Dados do cliente  
  .row
    .form-group
      = label_tag :cpf, I18n.t(:cpf), class: 'col-sm-2 control-label'
      .col-sm-4
        = text_field_tag :cpf, @cliente.cpf, class: 'form-control', readonly: true
    .form-group
      = label_tag :nome, I18n.t(:nome_cliente), class: 'col-sm-2 control-label'
      .col-sm-4
        = text_field_tag :nome, @cliente.nome, class: 'form-control', readonly: true
    .form-group
      = label_tag :email,  I18n.t(:email), class: 'col-sm-2 control-label'
      .col-sm-4
        = text_field_tag :email, @cliente.email, class: 'form-control', readonly: true 
  / Assinaturas do cliente
  .row
    %h1
      =I18n.t(:listing_assinaturas)
    = render '/assinaturas/table_assinaturas'
  