config/routes.rb
Myapp::Application.routes.draw do

  resources :marcas
  
  resources :modelos
  post 'modelos/get_modelos', to: 'modelos#get_modelos'
  
  resources :clientes 
  get '/search_cliente', to: "clientes#search"
  post 'clientes/verificar', to: "clientes#verificar"
  
  resources :assinaturas
  get 'assinaturas/index/:cliente_id', to: 'assinaturas#index', as: :cliente_assinaturas
 
  root to: 'static#index'
  
end

app/models/marca.rb
require 'rest-client'

class Marca < ActiveResource::Base  
  
  self.site = "https://assinatura-api.herokuapp.com/api/v1/" 

  #self.site = "tcp://localhost:3001/api/v1/" 

  self.element_name = "marca"
  has_many :modelos
  
  schema = {'nome' => :string }

  self.include_format_in_path = false

  
end

app/controllers/marcas_controller.rb
class MarcasController < ApplicationController
  before_action :set_marca, only: [:show, :edit, :update, :destroy]

  # GET /marcas
  # GET /marcas.json
  def index
    @marcas = Marca.all
    
    #@marcas = Pitzi.deserializer_colection(marcas)

  end

  # GET /marcas/1
  # GET /marcas/1.json
  def show
  end

  # GET /marcas/new
  def new
    @marca = Marca.new(nome: nil)
  end

  # GET /marcas/1/edit
  def edit

  end

  # POST /marcas
  # POST /marcas.json
  def create
    @marca = Marca.new(marca_params)

    if @marca.save
      redirect_to marcas_url, notice: I18n.t(:notice_marca_create) 
    else
      render :new 
    end
  end

  # PATCH/PUT /marcas/1
  # PATCH/PUT /marcas/1.json
  def update
    if @marca.update_attributes(marca_params)
      redirect_to marcas_url, notice: I18n.t(:notice_marca_update) 
    else
      render :edit 
    end
  end

  # DELETE /marcas/1
  # DELETE /marcas/1.json
  def destroy
    if @marca.destroy
      redirect_to marcas_url, notice: I18n.t(:notice_marca_destroy)
    else
      redirect_to marcas_url, notice: I18n.t(:notice_marca_not_destroy)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marca
      @marca = Marca.find(params[:id])
      #marca_json = Marca.find(params[:id])
      #marca_attrs = Pitzi.deserializer_object(marca_json)
      #@marca = Marca.new(marca_attrs.merge(persisted: true))
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marca_params
      params.require(:marca).permit(:nome)
    end
end

app/helpers/marcas_helper.rb
module MarcasHelper
end

app/views/marcas/_form.html.haml
= form_for @marca, html: { class: "form-horizontal", role: "form", id: 'form-marca' } do |f|
  -if @marca.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@marca.errors.count, "error")} prohibited this marca from being saved:"

      %ul
        - @marca.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label I18n.t(:nome_marca), class: 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :nome, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-4
      = f.submit class: 'btn btn-primary'
        

app/views/marcas/edit.html.haml
.page-header
  = link_to marcas_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    =I18n.t(:back)
  %h1
    =I18n.t(:editing_marca)

= render 'form'

app/views/marcas/index.html.haml
.page-header
  = link_to new_marca_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    =I18n.t(:new_marca)
  %h1
    =I18n.t(:listing_marcas)
.col-sm-6.table-responsive
  %table.table.table-striped.table-bordered.table-hover#dttb
    %thead
      %tr
        %th
          =I18n.t(:nome_marca)
        %th

    %tbody
      - @marcas.each do |marca|
        %tr
          /%td= marca.attributes[:attributes].nome
          %td= marca.nome
          %td
            = link_to edit_marca_path(marca) do
              %i.fa.fa-pencil
              =I18n.t(:edit)
              &nbsp;
              &nbsp;
            = link_to marca, data: { confirm: I18n.t(:are_you_sure_destroy_marca) }, method: :delete do
              %i.fa.fa-trash
              =I18n.t(:destroy)

app/views/marcas/new.html.haml
.page-header
  = link_to marcas_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1
    =I18n.t(:new_marca)

= render 'form'