config/routes.rb
Myapp::Application.routes.draw do

  resources :marcas
  
  resources :modelos
  post 'modelos/get_modelos', to: 'modelos#get_modelos'
  
  resources :clientes 
  get '/search_cliente', to: "clientes#search"
  post 'clientes/verificar', to: "clientes#verificar"
  
  resources :assinaturas
  get 'assinaturas/index/:cliente_id', to: 'assinaturas#index', as: :cliente_assinaturas
 
  root to: 'static#index'
  
end

app/models/assinatura.rb
class Assinatura < ActiveResource::Base  
  
  self.site = "https://assinatura-api.herokuapp.com/api/v1/" 

  #self.site = "tcp://localhost:3001/api/v1/" 

  self.element_name = "assinatura"

  belongs_to :modelo
  belongs_to :cliente
      
  schema = { 'imei' => :string, 'preco_anual' => :decimal, 'num_parcelas' => :integer,
           'status' => :integer, 'data_emisao' => :date, 'data_vencimento' => :date, 
           'modelo_id' => :integer, 'cliente_id' => :integer }

  self.include_format_in_path = false

  # Obtem as assinaturas para um cliente
  def self.cliente(cliente_id=0)
    return [] if cliente_id == 0
    url = "https://assinatura-api.herokuapp.com/api/v1/clientes/"+cliente_id.to_s+"/assinaturas"
    response = RestClient.get(url)
    json = JSON.parse(response.body)
  end

  def self.todas
    url = "https://assinatura-api.herokuapp.com/api/v1/assinaturas"
    response = RestClient.get(url)
    json = JSON.parse(response.body)
  end

end

app/controllers/assinaturas_controller.rb
class AssinaturasController < ApplicationController
  before_action :set_assinatura, only: [:show, :edit, :update, :destroy]

  # GET /assinaturas
  # GET /assinaturas.json
  def index
    if params[:cliente_id].nil?
      @assinaturas = Assinatura.todas
    else
      @assinaturas = Assinatura.cliente(params[:cliente_id])
    end
  end

  # GET /assinaturas/1
  # GET /assinaturas/1.json
  def show
  end

  # GET /assinaturas/new
  def new
    @assinatura = Assinatura.new(imei: nil, preco_anual: nil, num_parcelas: nil, modelo_id: nil,
                                cliente_id: nil, data_emisao: Date.today, data_vencimento: Date.today+365)
  end

  # GET /assinaturas/1/edit
  def edit
  end

  # POST /assinaturas
  # POST /assinaturas.json
  def create
    cliente_existe = true
    @cliente = Cliente.find(params[:cpf]) rescue nil
    if @cliente.nil?
      @cliente = Cliente.new(nome: params[:nome], cpf: params[:cpf], email: params[:email])
      if !@cliente.save
        cliente_existe = false
      end
    end 
    @assinatura = @assinatura = Assinatura.new(assinatura_params.merge(cliente_id: @cliente.id)) 
    if cliente_existe && @assinatura.save
      redirect_to assinaturas_url, notice: I18n.t(:notice_assinatura_create)
    else
      render :new 
    end
  end

  # PATCH/PUT /assinaturas/1
  # PATCH/PUT /assinaturas/1.json
  def update
    if @assinatura.update(assinatura_params)
      redirect_to assinaturas_url, notice: I18n.t(:notice_assinatura_update)
    else
      render :edit
    end
  end

  # DELETE /assinaturas/1
  # DELETE /assinaturas/1.json
  def destroy
    if @assinatura.destroy
      redirect_to assinaturas_url, notice: I18n.t(:notice_assinatura_destroy) 
    else
      redirect_to assinaturas_url, notice: I18n.t(:notice_assinatura_not_destroy) 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assinatura
      @assinatura = Assinatura.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assinatura_params
      params.require(:assinatura).permit(:imei, :preco_anual, :num_parcelas, :status, :data_emisao, :data_vencimento, :modelo_id, :cliente_id)
    end
end

app/helpers/assinaturas_helper.rb
module AssinaturasHelper
end

app/views/assinaturas/_form.html.haml
= form_for @assinatura, html: { class: "form-horizontal", role: "form" } do |f|
  -if @assinatura.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@assinatura.errors.count, "error")} prohibited this assinatura from being saved:"

      %ul
        - @assinatura.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label I18n.t(:nome_cliente), class: 'col-sm-2 control-label'
    .col-sm-4
      = f.select :cliente_id, options_from_collection_for_select(Cliente.all, :id, :nome, selected: f.object.cliente.present? ? f.object.cliente.id : nil), { include_blank: true }, {class: 'form-control'}
  .form-group
    = f.label I18n.t(:nome_modelo), class: 'col-sm-2 control-label'
    .col-sm-4
      = f.select :modelo_id, options_from_collection_for_select(Modelo.all, :id, :nome, selected: f.object.modelo.present? ? f.object.modelo.id : nil), { include_blank: true }, {class: 'form-control'}
  .form-group
    = f.label I18n.t(:imei), class: 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :imei, class: 'form-control'
  .form-group
    = f.label I18n.t(:preco_anual), class: 'col-sm-2 control-label'
    .col-sm-4
      = f.number_field :preco_anual, class: 'form-control'
  .form-group
    = f.label I18n.t(:num_parcelas), class: 'col-sm-2 control-label'
    .col-sm-4
      = f.number_field :num_parcelas, class: 'form-control'
  .form-group
    = f.label I18n.t(:data_emisao), class: 'col-sm-2 control-label'
    .col-sm-4
      = f.date_field :data_emisao, class: 'form-control'
  .form-group
    = f.label I18n.t(:data_vencimento), class: 'col-sm-2 control-label'
    .col-sm-4
      = f.date_field :data_vencimento, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-4
      = f.submit class: 'btn btn-primary'

app/views/assinaturas/_form_cliente_assinatura.html.haml
= form_for @assinatura, html: { class: "form-horizontal", role: "form", id: 'form-cliente-assinatura' } do |f|
  -if @assinatura.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@assinatura.errors.count, "error")} prohibited this assinatura from being saved:"

      %ul
        - @assinatura.errors.full_messages.each do |msg|
          %li= msg
  / Campos do formulario Cliente
  %h3 Dados do Cliente
  .form-group
    = label_tag :cpf, I18n.t(:cpf_cliente), class: 'col-sm-2 control-label'
    .col-sm-4
      = number_field_tag :cpf, "", class: 'form-control'
  .form-group
    = label_tag :nome, I18n.t(:nome_cliente), class: 'col-sm-2 control-label'
    .col-sm-4
      = text_field_tag :nome, '', class: 'form-control'
  .form-group
    = label_tag :email, I18n.t(:email), class: 'col-sm-2 control-label'
    .col-sm-4
      = text_field_tag :email, "", class: 'form-control'
  / Campos do formulario Assinatura
  %h3 Dados da Assinatura
  .form-group
    = label_tag :marca, I18n.t(:nome_marca), class: 'col-sm-2 control-label'
    .col-sm-4
      = select_tag :marca_id, options_from_collection_for_select(Marca.all, :id, :nome), { include_blank: true, class: 'form-control', id: 'select-marca'}
  .box{style: 'display: none'}
    .form-group
      = f.label I18n.t(:nome_modelo), class: 'col-sm-2 control-label'
      .col-sm-4
        = f.select :modelo_id, options_from_collection_for_select(Modelo.all, :id, :nome, selected: f.object.modelo.present? ? f.object.modelo.id : nil), { include_blank: true }, {class: 'form-control', id: 'select-modelo'}
  .form-group
    = f.label I18n.t(:imei), class: 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :imei, class: 'form-control'
  .form-group
    = f.label I18n.t(:preco_anual), class: 'col-sm-2 control-label'
    .col-sm-4
      = f.number_field :preco_anual, class: 'form-control'
  .form-group
    = f.label I18n.t(:num_parcelas), class: 'col-sm-2 control-label'
    .col-sm-4
      = f.number_field :num_parcelas, class: 'form-control'
  .form-group
    = f.label I18n.t(:data_emisao), class: 'col-sm-2 control-label'
    .col-sm-4
      = f.date_field :data_emisao, class: 'form-control'
  .form-group
    = f.label I18n.t(:data_vencimento), class: 'col-sm-2 control-label'
    .col-sm-4
      = f.date_field :data_vencimento, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-4
      = f.submit class: 'btn btn-primary'

app/views/assinaturas/_table_assinaturas.html.haml
.table-responsive
  %table.table.table-striped.table-bordered.table-hover#dttb
    %thead
      %tr
        %th
          =I18n.t(:nome_cliente_abr)
        %th
          =I18n.t(:nome_marca_abr)
        %th
          =I18n.t(:nome_modelo_abr)
        %th
          =I18n.t(:imei)
        %th
          =I18n.t(:preco_anual)
        %th
          =I18n.t(:num_parcelas)
        %th
          =I18n.t(:data_emisao)
        %th
          =I18n.t(:data_vencimento)
        %th
          =I18n.t(:status)
        %th

    %tbody
      - @assinaturas.each do |assinatura|
        %tr
          - cliente_nome = Cliente.find(assinatura['cliente_id']).nome 
          - modelo = Modelo.find(assinatura['modelo_id']) 
          - marca_nome = Marca.find(modelo.marca_id).nome
          %td= cliente_nome
          %td= marca_nome
          %td= modelo.nome
          %td= assinatura['imei']
          %td= assinatura['preco_anual']
          %td= assinatura['num_parcelas']
          %td= assinatura['data_emisao']
          %td= assinatura['data_vencimento']
          %td= assinatura['status']
          %td
            /= link_to edit_assinatura_path(assinatura) do
            /  %i.fa.fa-pencil
            /  &nbsp;
            /= link_to assinatura, data: { confirm: I18n.t(:are_you_sure_destroy_assinatura) }, method: :delete do
            /  %i.fa.fa-trash

app/views/assinaturas/edit.html.haml
.page-header
  = link_to assinaturas_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    =I18n.t(:back)
  %h1
    =I18n.t(:editing_assinatura)

= render 'form'

app/views/assinaturas/index.html.haml
.page-header
  = link_to search_cliente_path, class: 'btn btn-primary', id: 'form-search-cliente' do
    %span.glyphicon.glyphicon-plus
    =I18n.t(:new_assinatura)
  %h1
    =I18n.t(:listing_assinaturas)
= render 'table_assinaturas'    

app/views/assinaturas/new.html.haml
.page-header
  = link_to assinaturas_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    =I18n.t(:back)
  %h1
    =I18n.t(:new_assinatura)
= render 'form_cliente_assinatura'

app/views/assinaturas/show.html.haml
.page-header
  = link_to assinaturas_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_assinatura_path(@assinatura), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show assinatura

%dl.dl-horizontal
  %dt Imei:
  %dd= @assinatura.imei
  %dt Preco anual:
  %dd= @assinatura.preco_anual
  %dt Num parcelas:
  %dd= @assinatura.num_parcelas
  %dt Status:
  %dd= @assinatura.status
  %dt Data emisao:
  %dd= @assinatura.data_emisao
  %dt Data vencimento:
  %dd= @assinatura.data_vencimento
  %dt Modelo:
  %dd= @assinatura.modelo_id
  %dt Cliente:
  %dd= @assinatura.cliente_id