config/routes.rb
Myapp::Application.routes.draw do

  resources :marcas
  
  resources :modelos
  post 'modelos/get_modelos', to: 'modelos#get_modelos'
  
  resources :clientes 
  get '/search_cliente', to: "clientes#search"
  post 'clientes/verificar', to: "clientes#verificar"
  
  resources :assinaturas
  get 'assinaturas/index/:cliente_id', to: 'assinaturas#index', as: :cliente_assinaturas
 
  root to: 'static#index'
  
end

app/views/layouts/_flash_message.html.haml
-flash.each do |message_type , message|
  .row.flashing_mall_rental
    .col-lg-12
      -unless message_type == 'recaptcha_error'
        %div{class: "alert alert-#{message_type} alert-dismissable"}
          %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
          %strong
            =message

:javascript
  setTimeout(function() {
      $('.flashing_pitzi').fadeOut(1000);
  }, 6000);

app/views/layouts/_footer.html.haml
.footer
  .pull-center.align-center
    %strong Pitzi Copyright © 2021

app/views/layouts/_navigation.html.haml
%nav.navbar-default.navbar-static-side{:role => "navigation"}
  .sidebar-collapse
    %ul#side-menu.nav
      %li.nav-header
        .dropdown.profile-element
          %span
            = image_tag 'logo_pitzi.png', height: 60, width: 150
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %span.clear
              %span.block.m-t-xs
                %strong.font-bold
                  %h3 Assinaturas

        .logo-element
          VL
      %li{class: is_active_controller('marcas')}
        = link_to marcas_path do
          %i.fa.fa-map-marker
          %span.nav-label
            = I18n.t(:marcas)
      %li{class: is_active_controller('modelos')}
        = link_to modelos_path do
          %i.fa.fa-map-marker
          %span.nav-label
            = I18n.t(:modelos)
      %li{class: is_active_controller('clientes')}
        = link_to clientes_path do
          %i.fa.fa-map-marker
          %span.nav-label
            = I18n.t(:clientes)
      %li{class: is_active_controller('assinaturas')}
        = link_to assinaturas_path do
          %i.fa.fa-map-marker
          %span.nav-label
            = I18n.t(:assinaturas)


 

app/views/layouts/_topnavbar.html.haml
.row.border-bottom
  %nav.navbar.navbar-static-top{:role => "navigation", :style => "margin-bottom: 0"}
    .navbar-header
      %a.navbar-minimalize.minimalize-styl-2.btn.btn-primary{:href => "#"}
        %i.fa.fa-bars
      %form.navbar-form-custom{:action => "", :method => "post", :role => "search"}
        .form-group
    %ul.nav.navbar-top-links.navbar-right
      %li
        = link_to root_path(locale: 'pt' ) do
          %i.fa.fa-flag
            Portugues
      %li
        = link_to root_path(locale: 'es' ) do
          %i.fa.fa-flag
            Español
      %li
        = link_to root_path(locale: 'en') do
          %i.fa.fa-flag
            English
      %li
        = link_to '#' do
          %i.fa.fa-sign-out
 

app/views/layouts/application.html.haml
%html
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= 'Pitzi-Assinaturas'
    = favicon_link_tag 'tree_icon.gif'
    / Include style per-controller - vendor plugins
    = stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css")
    / Main css styles
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload'
    / Main javascript files
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    = csrf_meta_tags
  %body
    / Wrapper
    #wrapper{class: "#{params[:controller]}.#{params[:action]}"}
      / Navigation
      = render 'layouts/navigation'
      / Page wraper
      #page-wrapper{class: "gray-bg #{@extra_class}"}
        / Page wrapper
        = render 'layouts/topnavbar'
        = render 'layouts/flash_message'
        / Main view
        = yield
        / Footer
        = render 'layouts/footer'

    / Include javascript per-controller - vendor plugins
    = javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js")
    / Include javascript per-view
    / For demo purpose we include javascript in view but you can easily start SeedProject and organize it with Rails asset pipeline as you want
    = yield :javascript